services:
  annotations_db:
    container_name: annotations_db
    image: postgres:16.1-alpine3.19
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=senha123
      - POSTGRES_DB=pg_annotations