services:
  annotations_db:
    container_name: annotations_db
    image: postgres:16.1-alpine3.19
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=senha123
      - POSTGRES_DB=pg_annotations
  
  annotations_api:
    container_name: annotations_api
    build:
      context: ./annotations-backend/
      dockerfile: Dockerfile
    depends_on:
      - annotations_db
    ports:
      - 80:80 
    restart: "always"   
    environment:
      - DATABASE_URL=postgresql://admin:senha123@annotations_db/pg_annotations?schema=public
      - API_PORT=80
